MTGMVC/Models/ErrorViewModel.cs
using System;

namespace MTGMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MTGMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MTGMVC.Models;

namespace MTGMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MTGMVC/Controllers/MagicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MTGMVC.Controllers
{
    //[Route("Magic/[controller]")]
    public class MagicController : Controller
    {


        public IActionResult CardSearch()
        {
            ViewData["Message"] = "Card Search";

            return View();
        }

        public IActionResult DisplayCards()
        {
            ViewData["Message"] = "Display Cards";

            return View();
        }

        public IActionResult DisplayCard()
        {
            ViewData["Message"] = "Display Card";

            return View();
        }

        public IActionResult DeckSettings()
        {
            ViewData["Message"] = "Deck Settings";

            return View();
        }

        public IActionResult DeckStats()
        {
            ViewData["Message"] = "Deck Stats";

            return View();
        }

        public IActionResult DisplayDecks()
        {
            ViewData["Message"] = "Display Decks";

            return View();
        }

        // GET: api/<controller>
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<controller>/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<controller>
        [HttpPost]
        public void Post([FromBody]string value)
        {
        }

        // PUT api/<controller>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/<controller>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

MTGMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MTGMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MTGMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

MTGMVC/Views/Magic/CardSearch.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

*@
<html>

<head>
    <style>
        #cardSearch {
            background-color:lightgray;
            border:1px solid black;
            /*border-radius: 10px 10px;*/
            margin: auto;
            padding: 10px;
            display: flex;
        }

        div {
            margin: 1px;
        }

        #btnSearchSubmit {
            float:right;
        }
    </style>
</head>

<body>
    <section id="cardSearch">

        <form>
            <div class="form-group col-sm-9">
                <label for="txtCardName">Card Name</label>
                <input type="text" id="txtCardName" name="CardName" class="form-control" />
            </div>

            <div class="form-group col-sm-2 col-xs-4">
                <label for="selRarity">Rarity</label>
                <select id="selRarity" class="form-control">
                    <option>Common</option>
                    <option>Uncommon</option>
                    <option>Rare</option>
                </select>
            </div>


            <div class="form-group col-sm-3 col-xs-4">
                <label for="selEdition">Edition</label>
                <select id="selEdition" class="form-control">
                    <option>M10</option>
                    <option>M11</option>
                    <option>M12</option>
                </select>
            </div>
            <div class="form-group col-sm-2 col-xs-1">
                <label for="cbJokes">
                    <input type="checkbox" id="cbJokes" />
                    Include Joke Sets?
                </label>
            </div>
            <div class="form-group col-sm-1 col-xs-3">
                <label for="txtPower">Power</label>
                <input type="text" id="txtPower" class="form-control" />
            </div>
            <div class="form-group col-sm-1 col-xs-3">
                <label for="txtToughness">Tougness</label>
                <input type="text" id="txtToughness" class="form-control" />
            </div>

            <div class="form-group col-sm-3 col-xs-5">
                <label for="txtConManaCost">Converted Mana Cost</label>
                <input type="number" id="txtConManaCost" class="form-control" />
            </div>
            <div class="form-group col-sm-2 col-xs-1">
                <label for="cbWhite">
                    <input type="checkbox" id="cbWhite" />
                    White
                </label>
            </div>
            <div class="form-group col-sm-2 col-xs-1">
                <label for="cbBlack">
                    <input type="checkbox" id="cbBlack" />
                    Black
                </label>
            </div>
            <div class="form-group col-sm-2 col-xs-1">
                <label for="cbRed">
                    <input type="checkbox" id="cbRed" />
                    Red
                </label>
            </div>
            <div class="form-group col-sm-2 col-xs-1">
                <label for="cbGreen">
                    <input type="checkbox" id="cbGreen" />
                    Green
                </label>
            </div>
            <div class="form-group col-sm-2 col-xs-1">
                <label for="cbBlue">
                    <input type="checkbox" id="cbBlue" />
                    Blue
                </label>
            </div>
            <div class="form-group col-sm-2 col-xs-1">
                <label for="cbExclusive">
                    <input type="checkbox" id="cbExclusive" />
                    Only Selcted Colors
                </label>
            </div>


            <div class="form-group col-sm-4 col-xs-5">
                <label for="selCardType">Select Card Types</label>
                <select class="form-control custom-select" id="selCardType" multiple size="3">
                    <option>Creature</option>
                    <option>Artifact</option>
                    <option>Enchantment</option>
                    <option>Sorcery</option>
                    <option>Instant</option>
                </select>
            </div>
            <div class="form-group col-sm-4 col-xs-5">
                <label for="selAbilities">Select Card Abilities</label>
                <select class="form-control custom-select" id="selAbilities" multiple size="3">
                    <option>Creature</option>
                    <option>Artifact</option>
                    <option>Enchantment</option>
                    <option>Sorcery</option>
                    <option>Instant</option>
                </select>
            </div>

            <div class="form-group">
                <input class="btn btn-primary" type="submit" id="btnSearchSubmit" value="Search" />
            </div>
        </form>


    </section>
</body>

</html>

MTGMVC/Views/Magic/DeckSettings.cshtml
@{
    ViewData["Title"] = "DeckSettings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeckSettings</h2>

MTGMVC/Views/Magic/DeckStats.cshtml
@{
    ViewData["Title"] = "DeckStats";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeckStats</h2>

MTGMVC/Views/Magic/DisplayCard.cshtml
@{
    ViewData["Title"] = "DisplayCard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayCard</h2>

MTGMVC/Views/Magic/DisplayCards.cshtml
@{
    ViewData["Title"] = "DisplayCards";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>

<head>

</head>
<body>

<h2>Dispaly Cards</h2>

</body>



</html>

MTGMVC/Views/Magic/DisplayDecks.cshtml
@{
    ViewData["Title"] = "DisplayDecks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayDecks</h2>

MTGMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MTGMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MTGMVC</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Magic" asp-action="DisplayCards">Cards</a></li>
                <li><a asp-area="" asp-controller="Magic" asp-action="DisplayDecks">Decks</a></li>
            </ul>
        </div>
    </div>
</nav>
@await Html.PartialAsync("/Views/Magic/CardSearch.cshtml")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MTGMVC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>